### ISSUE TITLE
TH_Cycles Configuration Page Exception

### ISSUE THREAD

**Issue by PatrickRitchie** [TrakHound/TrakHound#27]
Bug Type : Exception

Message : Collection was modified; enumeration operation may not execute.

Source : mscorlib
Help Link : 
Target Site : ThrowInvalidOperationException

Stack Trace :    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at TH_Cycles.ConfigurationPage.Page.LoadCollectedItems(List`1 dataItems)
   at TH_Cycles.ConfigurationPage.Page.LoadData(DataTable dt)
   at TH_Cycles.ConfigurationPage.Page.LoadConfiguration(DataTable dt)
   at TH_DeviceManager.EditPage.<>c__DisplayClass48_0.<LoadPage>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TrakHound_Client.App.Main()

[MLFBIEQKCB.zip]

(https://github.com/TrakHound/TrakHound/files/275355/MLFBIEQKCB.zip)
![sehgzeukts](https://cloud.githubusercontent.com/assets/13772118/15440728/04ee336a-1ea5-11e6-85ff-d38760f0482b.jpg)

**Comment by PatrickRitchie** [comment]
Fails when trying to edit the list that it is looping through. Added a ToList() to the enumerated list in order to loop through a separate instance of the list that it is trying to modify.

```c#

private void LoadCollectedItems(List<DataItem> dataItems)
{
	var newItems = new List<CollectedItem>();

	foreach (var dataItem in dataItems)
	{
		var item = new CollectedItem(dataItem);
		newItems.Add(item.Copy());
	}

	foreach (var newItem in newItems)
	{
		if (!CollectedItems.ToList().Exists(x => x.Id == newItem.Id)) CollectedItems.Add(newItem);
	}

        // foreach (var item in CollectedItems) - old line
	foreach (var item in CollectedItems.ToList())
	{
		if (!newItems.Exists(x => x.Id == item.Id)) CollectedItems.Remove(item);
	}

	CollectedItems.SupressNotification = true;
	CollectedItems.Sort();
	CollectedItems.SupressNotification = false;
}

```
