### ISSUE TITLE
TH_Parts Configuration Page Exception

### ISSUE THREAD

**Issue by PatrickRitchie** [TrakHound/TrakHound#28]
Bug Type : Exception

Message : Object reference not set to an instance of an object.

Source : TH_Parts
Help Link : 
Target Site : GetGeneratedEventValues

Stack Trace :    at TH_Parts.ConfigurationPage.Page.GetGeneratedEventValues(String Id) in C:\Users\jweaver\Documents\TrakHound\TrakHound\Server\Plugins\TH_Parts\ConfigurationPage\Page.xaml.cs:line 194
   at TH_Parts.ConfigurationPage.Page.PartsEventName_SelectionChanged(Object sender, SelectionChangedEventArgs e) in C:\Users\jweaver\Documents\TrakHound\TrakHound\Server\Plugins\TH_Parts\ConfigurationPage\Page.xaml.cs:line 272
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.SelectItemWithValue(Object value)
   at System.Windows.Controls.Primitives.Selector.CoerceSelectedValue(DependencyObject d, Object value)
   at System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged(DependencyObject d, DependencyProperty dp, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at TH_Parts.ConfigurationPage.Page.set_SelectedPartsEventName(Object value) in C:\Users\jweaver\Documents\TrakHound\TrakHound\Server\Plugins\TH_Parts\ConfigurationPage\Page.xaml.cs:line 260
   at TH_Parts.ConfigurationPage.Page.LoadPartsEventName(DataTable dt) in C:\Users\jweaver\Documents\TrakHound\TrakHound\Server\Plugins\TH_Parts\ConfigurationPage\Page.xaml.cs:line 292
   at TH_Parts.ConfigurationPage.Page.LoadData(DataTable dt) in C:\Users\jweaver\Documents\TrakHound\TrakHound\Server\Plugins\TH_Parts\ConfigurationPage\Page.xaml.cs:line 87
   at TH_Parts.ConfigurationPage.Page.LoadConfiguration(DataTable dt) in C:\Users\jweaver\Documents\TrakHound\TrakHound\Server\Plugins\TH_Parts\ConfigurationPage\Page.xaml.cs:line 75
   at TH_DeviceManager.EditPage.<>c__DisplayClass48_0.<LoadPage>b__0() in C:\Users\jweaver\Documents\TrakHound\TrakHound\Libraries\TH_DeviceManager\EditPage.xaml.cs:line 185
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TrakHound_Client.App.Main() in C:\Users\jweaver\Documents\TrakHound\TrakHound\Client\TrakHound-Client\obj\Debug\App.g.cs:line 0

![abpkuxowwv](https://cloud.githubusercontent.com/assets/13772118/15440751/34ab9a84-1ea5-11e6-87eb-e706831f4625.jpg)

[SPUWLNCIIR.zip](https://github.com/TrakHound/TrakHound/files/275358/SPUWLNCIIR.zip)

**Comment by PatrickRitchie** [comment]
Needs to check for null reference before attempting to access one of the object's properties

```c#

void GetGeneratedEventValues(string Id)
        {
            GeneratedEventValues.Clear();

            if (GeneratedEventItems != null)
            {
                var e = GeneratedEventItems.ToList().Find(x => x.Id == Id);
                if (e != null)
                {
                    // Add each Value
                    foreach (var value in e.Event.values)
                    {
                        // GeneratedEventValues.Add(value.result.value); - old line didn't check for null
                        if (value.result != null) GeneratedEventValues.Add(value.result.value);
                    }

                    // Add Default Value
                    if (e.Event.Default != null)
                    {
                        // GeneratedEventValues.Add(e.Event.Default.value); - old line didn't check for null
                        if (e.Event.Default != null) GeneratedEventValues.Add(e.Event.Default.value);
                    }
                }
            }
        }


```
