### ISSUE TITLE
TH_GeneratedData Generated Events Configuration Page Exception

### ISSUE THREAD

**Issue by PatrickRitchie** [TrakHound/TrakHound#29]
Bug Type : Exception

Message : Method not found: 'System.String TH_MTConnect.Components.DataItem.get_Category()'.

Source : TH_GeneratedData
Help Link : 
Target Site : .ctor

Stack Trace :    at TH_GeneratedData.GeneratedEvents.ConfigurationPage.Page.CollectedItem..ctor(DataItem dataItem)
   at TH_GeneratedData.GeneratedEvents.ConfigurationPage.Page.LoadCollectedItems(List`1 dataItems) in C:\Users\jweaver\Downloads\TrakHound-master\Server\Plugins\TH_GeneratedData\GeneratedEvents\ConfigurationPage\Page.xaml.cs:line 218
   at TH_GeneratedData.GeneratedEvents.ConfigurationPage.Page.LoadConfiguration(DataTable dt) in C:\Users\jweaver\Downloads\TrakHound-master\Server\Plugins\TH_GeneratedData\GeneratedEvents\ConfigurationPage\Page.xaml.cs:line 84
   at TH_DeviceManager.EditPage.<>c__DisplayClass48_0.<LoadPage>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TrakHound_Client.App.Main()

![bkkqdsagay](https://cloud.githubusercontent.com/assets/13772118/15440803/6fc7d7e0-1ea5-11e6-82fb-0ab1f6c69fa2.jpg)

[HUAQTPWHWK.zip](https://github.com/TrakHound/TrakHound/files/275361/HUAQTPWHWK.zip)

**Comment by PatrickRitchie** [comment]
Fails when trying to access a method that it can't find in the TH_MTConnect assembly. The TH_MTConnect assembly has had a few recent updates so there may have been an issue of the TH_GeneratedData assembly trying to access the older version of TH_MTConnect which didn't previously have the DataItem.Category property.

Possibly a failed update that caused the inconsistency between the assemblies.

```c#

public class CollectedItem : IComparable
        {
            public CollectedItem() { }

            public CollectedItem(DataItem dataItem)
            {
                Id = dataItem.Id;
                Name = dataItem.Name;


                Category = dataItem.Category.ToString(); // Line that fails. 

                // Category is an enum so it should always have a value to use for ToString()


                Type = dataItem.Type;

                if (Name != null) Display = Id + " : " + Name;
                else Display = Id;
            }

```
