### ISSUE TITLE
Add Device Manual Page Catalog Search Exception

### ISSUE THREAD

**Issue by PatrickRitchie** [TrakHound/TrakHound#30]
Bug Type : Exception

Message : Object reference not set to an instance of an object.

Source : TH_DeviceManager
Help Link : 
Target Site : FilterCatalog

Stack Trace :    at TH_DeviceManager.AddDevice.Pages.Manual.FilterCatalog()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TrakHound_Client.App.Main()

[GRMKLPKEUI.zip](https://github.com/TrakHound/TrakHound/files/275364/GRMKLPKEUI.zip)

![dyigwljtkz](https://cloud.githubusercontent.com/assets/13772118/15440844/a59b5c20-1ea5-11e6-8179-3f4a117ae007.jpg)

**Comment by PatrickRitchie** [comment]
Seems to fail on a 'null reference' possibly when trying to convert the search_TXT.Text using ToLower() when the text could be null. Added null checks to prevent this and cleaned up some other lines as this is fairly older code.

```c#

private void FilterCatalog()
{
	// string search = search_TXT.Text.ToLower();
	string search = search_TXT.Text;

	//if (search != String.Empty)
	if (!string.IsNullOrEmpty(search))
	{
		search = search.ToLower();

		string[] searchList = search.Split(' ');

		var filterList = new List<CatalogInfo>();

		foreach (string s in searchList)
		{
			List<CatalogInfo> items = catalogInfos.FindAll(
			x =>
			(TestFilter(x.Item.manufacturer, s) ||
			TestFilter(x.Item.model, s) ||
			TestFilter(x.Item.author, s) ||
			TestFilter(x.Item.description, s) ||
			TestFilter(x.Item.controller, s) ||
			TestFilter(x.Item.device_type, s))
			);

			foreach (var item in items)
			{
				//if (filterList.Find(x => x.Item.list_id == item.Item.list_id) == null) filterList.Add(item);
				if (!filterList.Exists(x => x.Item.list_id == item.Item.list_id)) filterList.Add(item);
			}
		}

		AddCatalogItems(filterList);
	}
	else
	{
		AddCatalogItems(catalogInfos);
	}
}

```
