### ISSUE TITLE
Table doesn't exist when using default SQLite file.

### ISSUE THREAD

**Issue by egregory13** [TrakHound/TrakHound#31]
When ran through debugger in Visual studio 2015.

`SQLite error (1): no such table: BYLMDSPCFM_oee`

Bug Type : Exception

Message : Index was outside the bounds of the array.

Source : TH_StatusTable
Help Link : 
Target Site : UpdateShiftSegments

Stack Trace :    at TH_StatusTable.StatusTable.UpdateShiftSegments(Object shiftSegmentData, DeviceInfo info)
   at TH_StatusTable.StatusTable.<>c__DisplayClass14_0.<UpdateStatus>b__1()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TrakHound_Client.App.Main()

![image](https://cloud.githubusercontent.com/assets/12191845/16134507/601f403e-33d2-11e6-9c88-260a1d74371a.png)

**Comment by PatrickRitchie** [comment]
The "no such table" error doesn't seem related to the exception since the assembly listed is TH_StatusTable (one of the dashboard pages). 

The "no such table" exception is from the TH_SQLite database plugin and gets thrown sometimes by TrakHound Client before the tables are created by TrakHound Server.

I'll look into what is causing the exception listed but we are in the process of removing that particular page and replacing it with a better design which will be available in the next version.

Thanks for the information on this and please feel free to use the Issues section for other bug reports or feature requests in the future.

**Comment by PatrickRitchie** [comment]
The TH_StatusTable dashboard page has been discontinued as of v1.13.0.
